# Project Name
TARGET = Veno-Echo

DEBUG = 1

# Sources
CPP_SOURCES = Veno-Echo.cpp scale.cpp taptempo.cpp DelayMulti.cpp LEDs.cpp QSPI_Settings.cpp oscillator_p.cpp

# Library Locations
LIBDAISY_DIR = ../libDaisy
DAISYSP_DIR = ../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

